#!/bin/sh
# Run sh ~/home/apt-requirements to install!
  cat "$HOME/home/zypper-requirements" | grep -ve '^#' -e '^ ' -e '^$' | sudo xargs -t zypper install
  exit 0

# base ~/home setup:
bat
curl
git
fd
file
fzf
jq
make
neovim
ripgrep
zsh

# Service CLIs
hub

# node:
nodejs12
npm12

# python:
pyenv
python3-devel
libffi7
libffi-devel
libunwind
libunwind-devel
python3-dbus-python-devel
python3-cairo-devel

# electron:
# TPDP

# Other language ecosystems:
ShellCheck
postgresql

# Pilot
pinentry
pinentry-gnome3
pinentry-qt
terraform
