#!/bin/sh
# Run sh ~/home/apt-requirements to install!
  cat "$HOME/home/zypper-requirements" | grep -ve '^#' -e '^ ' -e '^$' | sudo xargs -t zypper install
  # dpkg stub to run pilot:
  mkdir -p "$HOME/bin"
  echo '#!/bin/sh' > "$HOME/bin/dpkg"
  echo 'echo "dpkg-stub" "$@"' >> "$HOME/bin/dpkg"
  chmod u+x "$HOME/bin/dpkg"
  exit 0

# Base patterns:
pattern:base
pattern:enhanced_base
pattern:console
pattern:devel_basis
pattern:devel_C_C++
pattern:documentation
pattern:fonts
pattern:x11
pattern:gnome
pattern:gnome_basic
pattern:gnome_x11
pattern:yast2_basis

# openSUSE system misc
openSUSE-release
release-notes-openSUSE
grub2-x86_64-efi

# cli essentials
zsh
vim
git
make

# ~/home setup:
bat
fd
fzf
vim-fzf
jq
neovim
ripgrep
tig
mosh

# Service CLIs
hub

# node:
nodejs14
npm14

# python:
pattern:devel_python3
pyenv
libffi-devel
libunwind
libunwind-devel
python3-dbus-python-devel

# electron:
# TPDP

# Other language ecosystems:
ShellCheck
postgresql
docker

# Pilot
openssl
pinentry
pinentry-gnome3
pinentry-qt5
terraform
words

# Applications
gnome-terminal
MozillaFirefox
chromium
epiphany
powertop
vnstat
