#!/bin/bash
set -euo pipefail
mkdir --mode=700 /dev/shm/zypper-clean
cd /dev/shm/zypper-clean

recurse_through_requests() {
  echo '' > last_requested
  cat requested | sed 's/^pattern:/pattern() = /' | xargs -d '\n' zypper search -if --provides --match-exact | grep '^i' | cut -d '|' -f 2 | tr -d ' ' > needed
  while ! diff last_requested needed >/dev/null; do
    mv needed last_requested
    cat last_requested | xargs -d '\n' rpm -q --requires --recommends > requires
    cat requires | xargs -d '\n' zypper search -if --provides --match-exact | grep '^i' | cut -d '|' -f 2 | tr -d ' ' > provides
    cat last_requested provides | sort | uniq > needed
  done
}

zypper pt -i | grep '^i' | cut -d '|' -f 2 | tr -d ' ' | sed s/^/pattern:/ > installed
zypper pa -i | grep '^i' | cut -d '|' -f 3 | tr -d ' ' >> installed

#cat "$HOME/home/zypper-requirements" | grep -ve '^#' -e '^ ' -e '^$' > requested
echo 'pattern:gnome' > requested

recurse_through_requests

cat needed | xargs -d '\n' zypper search -i -t package --supplements | grep '^i' | cut -d '|' -f 2 | tr -d ' ' > supplements
cat needed supplements | sort | uniq > important
cat installed needed | sort | uniq -u > autoinstalled

#autoinstalled=$(printf '%s\n%s\n' "${installed}" "${important}" | sort | uniq -u)
#
#echo "$autoinstalled" | sudo tee /var/lib/zypp/AutoInstalled > /dev/null
#echo "Updated /var/lib/zypp/AutoInstalled"
#
#zypper pa -r repo-oss --unneeded
