#!/bin/bash
set -euo pipefail

recurse_through_requests() {
  echo '' > .cache/last_requested
  cat .cache/requested | sed 's/^pattern:/pattern() = /' | xargs -d '\n' zypper search -i --provides --match-exact | grep '^i' | cut -d '|' -f 2 | tr -d ' ' > .cache/needed
  while ! diff .cache/last_requested .cache/needed; do
    mv .cache/needed .cache/last_requested
    cat .cache/last_requested | xargs -d '\n' rpm -q --requires --recommends > .cache/requires
    cat .cache/requires | xargs -d '\n' zypper search -i --provides --match-exact | grep '^i' | cut -d '|' -f 2 | tr -d ' ' > .cache/provides
    cat .cache/last_requested .cache/provides | sort | uniq > .cache/needed
  done
}

zypper pt -i | grep '^i' | cut -d '|' -f 2 | tr -d ' ' | sed s/^/pattern:/ > .cache/installed
zypper pa -i | grep '^i' | cut -d '|' -f 3 | tr -d ' ' >> .cache/installed

cat "$HOME/home/zypper-requirements" | grep -ve '^#' -e '^ ' -e '^$' > .cache/requested

recurse_through_requests

cat .cache/needed | xargs -d '\n' zypper search -i -t package --supplements | grep '^i' | cut -d '|' -f 2 | tr -d ' ' > .cache/supplements
cat .cache/needed .cache/supplements | sort | uniq > .cache/important
cat .cache/installed .cache/needed | sort | uniq -u > .cache/autoinstalled

#autoinstalled=$(printf '%s\n%s\n' "${installed}" "${important}" | sort | uniq -u)
#
#echo "$autoinstalled" | sudo tee /var/lib/zypp/AutoInstalled > /dev/null
#echo "Updated /var/lib/zypp/AutoInstalled"
#
#zypper pa -r repo-oss --unneeded
