#!/bin/sh
# Run sh ~/home/apt-requirements to install!
  cat "$HOME/home/zypper-requirements" | grep -ve '^#' -e '^ ' -e '^$' | sudo xargs -t zypper install
  # dpkg stub to run pilot:
  mkdir -p "$HOME/bin"
  echo '#!/bin/sh' > "$HOME/bin/dpkg"
  echo 'echo "dpkg-stub" "$@"' >> "$HOME/bin/dpkg"
  chmod u+x "$HOME/bin/dpkg"
  exit 0

# Base patterns:
pattern:base
pattern:enhanced_base
pattern:console
pattern:devel_basis
pattern:devel_C_C++
pattern:documentation
pattern:fonts
pattern:gnome
pattern:yast2_basis

# cli essentials
curl
file
gcc
git
glibc
make
zsh

# ~/home setup:
bat
fd
fzf
vim-fzf
jq
neovim
ripgrep

# Service CLIs
hub

# node:
nodejs12
npm12

# python:
python3-devel
libffi-devel
libunwind
libunwind-devel
python3-dbus-python-devel
python3-cairo-devel

# electron:
# TPDP

# Other language ecosystems:
ShellCheck
postgresql
docker

# Pilot
openssl
pinentry
pinentry-gnome3
pinentry-qt
terraform
words

# Applications
epiphany
