# Allow things from homebrew core or casks
tap "homebrew/cask"
cask_args appdir: "/Applications"

# User software
#cask "chromium"

# Language ecosystems:
brew "node@16", link: true
brew "python"
brew "pyenv"
brew "lua"
brew "postgres"
brew "shellcheck"
brew "terraform"
brew "yarn"

# Standard util polyfills for mac:
brew "gnupg"
brew "libpng"

# Better Utils:
brew "neovim"
brew "ripgrep"
brew "fd"
brew "jq"
brew "tig"
brew "fzf"
brew "bat"
brew "git-delta"

# Service CLIs:
brew "gh" # GitHub new
brew "hub" # GitHub legacy
brew "awscli" # AWS
brew "docker-credential-helper-ecr" # Docker creds helper; make sure to update ~/.docker/config.json
