#!/bin/zsh
# Load zsh "hooks": settings to load depending on what programs exist
# on the host
#
# From https://gist.io/@tsutsu/2c11fc0a36000a46566e9fd62c60dea4

if [[ -z "$HOOKS_LOADED" ]]; then
  export HOOKS_LOADED=":"

  if [[ -d "$HOME/.zsh/hooks" ]]; then
    for hook_script in "$HOME/.zsh/hooks/"*; do
      if [[ ! -x "${hook_script}" ]] && [[ "${hook_script: -3}" != ".sh" ]]; then
        continue
      fi

      reqs=($(basename "${hook_script}" | sed 's/\.sh$//' | tr '+' "\n"))
      satisfied_reqs=0

      for req in "${reqs[@]}"; do
        if [[ "${req:0:1}" == "-" ]]; then
          # If req is `ag+-rg`, then it means we have ag but we don't have rg:
          if ! hash "${req:1}" 2>/dev/null; then
            satisfied_reqs="$((satisfied_reqs+1))"
          fi
        elif hash "${req}" 2>/dev/null; then
          # Normal check for dep:
          satisfied_reqs="$((satisfied_reqs+1))"
        fi
      done

      if [[ "${#reqs[@]}" -eq "${satisfied_reqs}" ]]; then
        export HOOKS_LOADED="${HOOKS_LOADED}$(basename ${hook_script}):"
        source "${hook_script}"
      fi
    done
  fi
fi
